[dev]
token = "MTI0ODU5NTQ3MD******************************************"
status = ""
database = "sqlite+aiosqlite:///dev.db"
admins = []
forum_id = 1296799924742262804
staff_role = 1297167463796051978


[prod]
token = ""
database = "sqlite+aiosqlite:///dev.db"
status = ""
admins = []
forum_id = ""
staff_role = ""

